[build]
builder = "NIXPACKS"

# Setup Python and Node environment
buildCommand = """
python -m pip install --upgrade pip && \
pip install -r backend/requirements.txt && \
cd backend && \
npm ci && \
NODE_ENV=production npm run build
"""

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
