"""add_user_feed_relationship

Revision ID: 48ab6f3e1841
Revises: set_default_admin_values
Create Date: 2025-01-28 13:22:23.994961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48ab6f3e1841'
down_revision: Union[str, None] = 'set_default_admin_values'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source_id', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('api_source', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('articles', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_column('articles', 'extra_data')
    op.drop_column('articles', 'author')
    op.drop_column('articles', 'category')
    op.drop_column('articles', 'api_source')
    op.drop_column('articles', 'source_id')
    # ### end Alembic commands ###